### ISSUE TITLE
Airflow start failure - /usr/bin/env: ‘bash\r’: No such file or directory

### ISSUE THREAD

**Issue by DylDelport** [konosp/dbt-airflow-docker-compose#1]
Getting the following error: /usr/bin/env: ‘bash\r’: No such file or directory.

The container is stuck in a loop restarting.

Following this article:
Steps followed:
1) Cloned repo
2) extracted sample files
3) Opened terminal and ran 'docker-compose up'

Got the following response in the terminal.

> Creating network "dbt-airflow-docker-compose_default" with the default driver
Creating dbt-airflow-docker-compose_postgres-airflow_1 ... done                               Creating dbt-airflow-docker-compose_postgres-dbt_1     ... done                               Creating dbt-airflow-docker-compose_airflow_1          ... done                               Creating dbt-airflow-docker-compose_adminer_1          ... done                               Attaching to dbt-airflow-docker-compose_postgres-dbt_1, dbt-airflow-docker-compose_postgres-airflow_1, dbt-airflow-docker-compose_airflow_1, dbt-airflow-docker-compose_adminer_1
adminer_1           | [Wed Oct 28 16:35:43 2020] PHP 7.4.11 Development Server (http://[::]:8080) started
airflow_1           | /usr/bin/env: ‘bash\r’: No such file or directory
postgres-airflow_1  | The files belonging to this database system will be owned by user "postgres".
postgres-airflow_1  | This user must also own the server process.
postgres-dbt_1      | The files belonging to this database system will be owned by user "postgres".
postgres-dbt_1      | This user must also own the server process.
postgres-dbt_1      |
postgres-dbt_1      | The database cluster will be initialized with locale "en_US.utf8".
postgres-dbt_1      | The default database encoding has accordingly been set to "UTF8".
postgres-dbt_1      | The default text search configuration will be set to "english".
postgres-dbt_1      |
postgres-dbt_1      | Data page checksums are disabled.
postgres-dbt_1      |
postgres-dbt_1      | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres-dbt_1      | creating subdirectories ... ok
postgres-airflow_1  |
postgres-dbt_1      | selecting dynamic shared memory implementation ... posix
postgres-airflow_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres-airflow_1  | The default database encoding has accordingly been set to "UTF8".
postgres-airflow_1  | The default text search configuration will be set to "english".
postgres-airflow_1  |
postgres-airflow_1  | Data page checksums are disabled.
postgres-airflow_1  |
postgres-dbt_1      | selecting default max_connections ... 100
postgres-dbt_1      | selecting default shared_buffers ... 128MB
postgres-airflow_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres-dbt_1      | selecting default time zone ... Etc/UTC
postgres-dbt_1      | creating configuration files ... ok
postgres-dbt_1      | running bootstrap script ... ok
postgres-dbt_1      | performing post-bootstrap initialization ... ok
postgres-airflow_1  | creating subdirectories ... ok
postgres-airflow_1  | selecting dynamic shared memory implementation ... posix
postgres-airflow_1  | selecting default max_connections ... 100
postgres-airflow_1  | selecting default shared_buffers ... 128MB
postgres-airflow_1  | selecting default time zone ... Etc/UTC
postgres-airflow_1  | creating configuration files ... ok
postgres-airflow_1  | running bootstrap script ... ok
postgres-airflow_1  | performing post-bootstrap initialization ... ok
postgres-airflow_1  | syncing data to disk ... ok
postgres-airflow_1  |
postgres-airflow_1  |
postgres-airflow_1  | Success. You can now start the database server using:
postgres-airflow_1  |
postgres-airflow_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres-airflow_1  |
postgres-airflow_1  | initdb: warning: enabling "trust" authentication for local connections
postgres-airflow_1  | You can change this by editing pg_hba.conf or using the option -A, or
postgres-airflow_1  | --auth-local and --auth-host, the next time you run initdb.
postgres-airflow_1  | waiting for server to start....2020-10-28 16:35:43.740 UTC [46] LOG:  starting PostgreSQL 13.0 (Debian 13.0-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
postgres-airflow_1  | 2020-10-28 16:35:43.742 UTC [46] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres-airflow_1  | 2020-10-28 16:35:43.748 UTC [47] LOG:  database system was shut down at 2020-10-28 16:35:43 UTC
postgres-airflow_1  | 2020-10-28 16:35:43.753 UTC [46] LOG:  database system is ready to accept connections
postgres-airflow_1  |  done
postgres-airflow_1  | server started
postgres-dbt_1      | syncing data to disk ... initdb: warning: enabling "trust" authentication for local connections
postgres-dbt_1      | You can change this by editing pg_hba.conf or using the option -A, or
postgres-dbt_1      | --auth-local and --auth-host, the next time you run initdb.
postgres-dbt_1      | ok
postgres-dbt_1      |
postgres-dbt_1      |
postgres-dbt_1      | Success. You can now start the database server using:
postgres-dbt_1      |
postgres-dbt_1      |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres-dbt_1      |
postgres-dbt_1      | waiting for server to start....2020-10-28 16:35:43.944 UTC [46] LOG:  starting PostgreSQL 13.0 (Debian 13.0-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
postgres-dbt_1      | 2020-10-28 16:35:43.948 UTC [46] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres-dbt_1      | 2020-10-28 16:35:43.956 UTC [47] LOG:  database system was shut down at 2020-10-28 16:35:43 UTC
postgres-dbt_1      | 2020-10-28 16:35:43.962 UTC [46] LOG:  database system is ready to accept connections
postgres-dbt_1      |  done
postgres-dbt_1      | server started
postgres-airflow_1  | CREATE DATABASE
postgres-airflow_1  |
postgres-airflow_1  |
postgres-airflow_1  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init-user-db.sh
postgres-airflow_1  | /usr/local/bin/docker-entrypoint.sh: /docker-entrypoint-initdb.d/init-user-db.sh: /bin/bash^M: bad interpreter: No such file or directory
postgres-dbt_1      | CREATE DATABASE
postgres-dbt_1      |
postgres-dbt_1      |
postgres-dbt_1      | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres-dbt_1      |
postgres-dbt_1      | waiting for server to shut down...2020-10-28 16:35:44.324 UTC [46] LOG:  received fast shutdown request
postgres-dbt_1      | .2020-10-28 16:35:44.328 UTC [46] LOG:  aborting any active transactions
postgres-dbt_1      | 2020-10-28 16:35:44.331 UTC [46] LOG:  background worker "logical replication launcher" (PID 53) exited with exit code 1
postgres-dbt_1      | 2020-10-28 16:35:44.337 UTC [48] LOG:  shutting down
postgres-dbt_1      | 2020-10-28 16:35:44.370 UTC [46] LOG:  database system is shut down
postgres-dbt_1      |  done
postgres-dbt_1      | server stopped
postgres-dbt_1      |
postgres-dbt_1      | PostgreSQL init process complete; ready for start up.
postgres-dbt_1      |
postgres-dbt_1      | 2020-10-28 16:35:44.460 UTC [1] LOG:  starting PostgreSQL 13.0 (Debian 13.0-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
postgres-dbt_1      | 2020-10-28 16:35:44.461 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres-dbt_1      | 2020-10-28 16:35:44.461 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres-dbt_1      | 2020-10-28 16:35:44.466 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres-dbt_1      | 2020-10-28 16:35:44.476 UTC [64] LOG:  database system was shut down at 2020-10-28 16:35:44 UTC
postgres-dbt_1      | 2020-10-28 16:35:44.487 UTC [1] LOG:  database system is ready to accept connections
dbt-airflow-docker-compose_airflow_1 exited with code 127
postgres-airflow_1  |
postgres-airflow_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres-airflow_1  |
postgres-airflow_1  | 2020-10-28 16:35:44.854 UTC [1] LOG:  starting PostgreSQL 13.0 (Debian 13.0-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
postgres-airflow_1  | 2020-10-28 16:35:44.854 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres-airflow_1  | 2020-10-28 16:35:44.854 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres-airflow_1  | 2020-10-28 16:35:44.860 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres-airflow_1  | 2020-10-28 16:35:44.869 UTC [25] LOG:  database system was interrupted; last known up at 2020-10-28 16:35:44 UTC
postgres-airflow_1  | 2020-10-28 16:35:45.251 UTC [25] LOG:  database system was not properly shut down; automatic recovery in progress
postgres-airflow_1  | 2020-10-28 16:35:45.253 UTC [25] LOG:  redo starts at 0/15CE7D0
postgres-airflow_1  | 2020-10-28 16:35:45.253 UTC [25] LOG:  invalid record length at 0/15CE8C8: wanted 24, got 0
postgres-airflow_1  | 2020-10-28 16:35:45.253 UTC [25] LOG:  redo done at 0/15CE880
postgres-airflow_1  | 2020-10-28 16:35:45.271 UTC [1] LOG:  database system is ready to accept connections
dbt-airflow-docker-compose_airflow_1 exited with code 127
dbt-airflow-docker-compose_airflow_1 exited with code 127
dbt-airflow-docker-compose_airflow_1 exited with code 127
dbt-airflow-docker-compose_airflow_1 exited with code 127
dbt-airflow-docker-compose_airflow_1 exited with code 127
dbt-airflow-docker-compose_airflow_1 exited with code 127

**Comment by konosp** [comment]
Hi @DylDelport i think the issue relates to the problem mentioned at the below git link.

https://stackoverflow.com/a/48165262
Do you mind checkkng the below and let me know if it works?

I might to update the docker-compose.yml file.

**Comment by DylDelport** [comment]
Thanks, @konosp, will give that a try and let you know.

**Comment by kdickinson87** [comment]
I was pulling my hair out for an hour trying to fix this. Remember. Once you run docker-compose up, and get the above error, you have to delete the dbt-airflow-docker-compose_airflow image. 

My issue was, when I cloned to my windows PC, git autoconverted the endings to CRLF. I got them converted back but still kept running into issues with the above error. That's when I remembered you have to delete the image created in the dockerfile, because it still has the old init.sh that was copied over with the CRLF contained within.

I would recommend, at minimum, adding a note in the readme for windows users to either convert the CRLF back to LF, or to have their git setup to not auto-convert. 

Best thing would be to add a .gitattributes file to the repo that sets the auto-convert to false, that way every system is happy. I can create it and submit a PR for it if you'd like.

**Comment by konosp** [comment]
Hi @kdickinson87 , thank you for your feedback, appreciate it!
Yes please, create a PR for it, I have not faced this issue before and I do not have a Win PC to try this unfortunately.

Cheers!
